apiVersion: v1
kind: Service
metadata:
  name: url-shortener-kv-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: url-shortener-kv-store
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP