apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  REDIS_URI: "redis://url-shortener-kv-service.url-shortener.svc.cluster.local:6379"
  PORT: "5000"