apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
  namespace: url-shortener
  labels:
    app: url-shortener-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-backend
  template:
    metadata:
      labels:
        app: url-shortener-backend
    spec:
      containers:
      - name: url-shortener-backend
        image: shanbhagsohan/url-shortener:backend
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: url-shortener-config
      imagePullSecrets:
        - name: regcred
