apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend-service
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-shortener-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
