apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-frontend
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-frontend
  template:
    metadata:
      labels:
        app: url-shortener-frontend
    spec:
      containers:
      - name: url-shortener-frontend
        image: shanbhagsohan/url-shortener:frontend
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: url-shortener-config
      imagePullSecrets:
        - name: regcred
