apiVersion: v1
kind: Service
metadata:
  name: url-shortener-frontend-service
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-shortener-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
